# Generated by Django 6.0 on 2025-12-26 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordwolf', '0002_room_category_room_discussion_time_alter_member_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='max_user_num',
        ),
    ]
